const config = {
    deleteElem: 'jsDelete',
    editElem: 'jsEdit',
    invisibleClass: 'invisible',
    mainContentClass: 'mainContent',
    gameInfo: 'jsGameInfo',
    rentGame: 'jsRentGame',
    returnGame: 'jsReturnGame',
    closeElement: 'jsClose',
    gameIDAtr: 'gameid',
    overlayClass: 'overlay',
    accountPage: {
        userInfo: 'userInfo',
        addressID: 'ADDRESS_ID',
        userID: 'USER_ID',
        dataClass: 'account-data',
        columnClass: 'account-data_column',
        labelsClass: 'account-data_label',
        inputClass: 'account-data_input',
        invalidInputClass: 'account-data_input--invalid',
        menuClass: 'account-menu',
        menuLinkClass: 'account-menu--link',
        dataDependency: 'dependency',
        dependencyArray: ['Account', 'Games', 'Achievements'],
        userData: {
            name: 'userData',
            order: ['NAME', 'LAST_NAME'],
            labels: {
                NAME: 'Imie',
                LAST_NAME: 'Nazwisko',
            },
        },
        address: {
            name: 'address',
            order: ['CITY', 'STREET', 'ZIP', 'PHONE'],
            labels: {
                CITY: 'Miasto',
                STREET: 'Ulica',
                ZIP: 'ZIP',
                PHONE: 'Telefon',
            },
        },
    },
    menuConfig: {
        menuClass: 'menu',
        menuLink: 'menu--link',
        dataDependency: 'dependency',
        dependencyArray: ['account', 'games', 'contact', 'logout', 'admin'],
    },
    gamesConfig: {
        gamesFiltersClass: 'games-filters',
        filterInputsClass: 'games-filters_inputs',
        categoriesCheckboxes: 'games-filters_checkbox',
        min: 'min',
        max: 'max',
        category: 'category',
        availability: 'availability',
    },
    tableConfig: {
        tableClass: 'table',
        tableBodyClass: 'table_body',
        tableHeaderClass: 'table_header',
    },
    infoOverlayConfig: {
        listValues: [
            {
                label: 'Kategoria:',
                key: 'CATEGORY',
            },
            {
                label: 'Liczba graczy:',
                key: 'NUMBER_OF_PLAYERS',
            },
            {
                label: 'Czas gry:',
                key: 'GAME_TIME',
            },
            {
                label: 'Opłata:',
                key: 'BAIL',
            },
        ],
        stars: ['00', '10', '15', '20', '25', '30', '35', '40', '45', '50'],
        starClass: 'star',
        gameRating: 'gameRating',
        yourRating: 'yourRating',
        ratingConfig: [
            {
                label: 'Ocena',
                id: 'gameRating',
                isDisabled: true,
            },
            {
                label: 'Twoja ocena',
                id: 'yourRating',
                isDisabled: false,
            },
        ],
    },
    adminConfig: {
        sidePanelClass: 'admin-sidePanel',
        adminMenuClass: 'admin-menu',
        adminMenuListClass: 'admin-menu_list',
        adminMenuItemClass: 'admin-menu_item',
        adminMenuLinkClass: 'admin-menu_link',
        menuElements: [
            {
                dependency: 'games',
                label: 'Gry',
            }, {
                dependency: 'users',
                label: 'Użytkownicy',
            }, {
                dependency: 'categories',
                label: 'Kategorie',
            },
            {
                dependency: 'shops',
                label: 'Sklepy',
            },
            {
                dependency: 'achievements',
                label: 'Osiągnięcia',
            },
        ],
        dependency: 'dependency',
        dependencyArray: ['games', 'shops', 'users', 'achievements', 'categories'],
        adminMainContentClass: 'admin-mainContent',
        buttonsClass: 'admin-buttons',
        buttonClass: 'admin-buttons_button',
        adminContentClass: 'admin-content',
        games: {
            name: 'games',
            button: 'Dodaj grę',
            header: 'Gry:',
            id: 'GAME_ID',
            columnNames: ['Tytuł', 'Kategoria', 'Dostępność', 'Akcja'],
            order: ['TITLE', 'CATEGORY', 'AVAILABILITY'],
            condition: 'AVAILABILITY',
            actions: [
                {
                    name: 'edit',
                    label: 'Edytuj',
                    actionClass: 'editElem',
                },
                {
                    name: 'delete',
                    label: 'Usuń',
                    actionClass: 'deleteElem',
                },
            ],
            query: 'getAllGames',
            queryResult: 'getGames',
        },
        users: {
            name: 'users',
            header: 'Użytkownicy',
            id: 'USER_ID',
            columnNames: ['Nick', 'Imię', 'Nazwisko', 'Akcja'],
            order: ['USER_ID', 'NAME', 'LAST_NAME'],
            condition: 'HasEverythingReturned',
            actions: [
                {
                    name: 'delete',
                    label: 'Usuń',
                    actionClass: 'deleteElem',
                },
            ],
            query: 'getAllUsers',
            queryResult: 'getUsers',
        },
        categories: {
            name: 'categories',
            header: 'Kategorie',
            id: 'CATEGORY_ID',
            button: 'Dodaj kategorię',
            columnNames: ['Nazwa', 'Akcja'],
            order: ['NAME'],
            actions: [
                {
                    name: 'edit',
                    label: 'Edytuj',
                    actionClass: 'editElem',
                },
                {
                    name: 'delete',
                    label: 'Usuń',
                    actionClass: 'deleteElem',
                },
            ],
            query: 'getCategories',
            queryResult: 'getCategories',
        },
        shops: {
            name: 'shops',
            header: 'Sklepy',
            id: 'SHOP_ID',
            button: 'Dodaj sklep',
            columnNames: ['Miasto', 'Ulica', 'ZIP', 'Telefon', 'Akcja'],
            order: ['ADDRESS.CITY', 'ADDRESS.STREET', 'ADDRESS.ZIP', 'ADDRESS.PHONE'],
            actions: [
                {
                    name: 'edit',
                    label: 'Edytuj',
                    actionClass: 'editElem',
                },
                {
                    name: 'delete',
                    label: 'Usuń',
                    actionClass: 'deleteElem',
                },
            ],
            query: 'getAllShops',
            queryResult: 'getShops',
        },
        achievements: {
            name: 'achievements',
            header: 'Osiągnięcia',
            button: 'Dodaj osiągnięcie',
            id: 'NAME',
            columnNames: ['Nazwa', 'Warunek', 'Akcja'],
            order: ['NAME', 'CONDITION'],
            actions: [
                {
                    name: 'edit',
                    label: 'Edytuj',
                    actionClass: 'editElem',
                },
                {
                    name: 'delete',
                    label: 'Usuń',
                    actionClass: 'deleteElem',
                },
            ],
            query: 'getAllAchievements',
            queryResult: 'getAchievements',
        },
    },
};

export default config;